[server]
maxMessageSize = 1000
maxUploadSize = 1000
enableCORS = false
enableXsrfProtection = false
headless = true

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
